// <auto-generated />
namespace AlugaGo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Migri04Dez : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migri04Dez));
        
        string IMigrationMetadata.Id
        {
            get { return "201712042156245_Migri04Dez"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
